version: '3.3'
services:
  firefox:
    container_name: firefox
    ports:
      - '1001:5800'
    volumes:
      - './firefox:/config:rw'
    environment:
      - LANG=zh_CN.UTF-8
    image: jlesage/firefox